baseurl = "https://the-red-oven.netlify.app"
title = "The Red Oven"
author = "Lynn Stuart"
canonifyurls = true
paginate = 3
theme = "aether"
themesDir = "themes" 

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[params]
    brand = "The Red Oven"
    description = "A blog about..."
    bgimg = "img/ignasi_pattern_s.png"
    favicon = ""
    site_logo = ""
    facebook = ""
    twitter = "https://twitter.com/GoHugoIO"
    instagram = ""
    youtube = ""
    github = ""
    gitlab = ""
    linkedin = ""
    mastodon = ""
    slack = ""
    stackoverflow = ""
    rss = ""

[markup]
  [markup.highlight]
    style = "igor"
