baseurl = "https://the-red-oven.netlify.app"
title = "The Red Oven"
author = "Lynn Stuart"
canonifyurls = true
paginate = 3
theme = "aether"
themesDir = "themes" 

[params]
    brand = "The Red Oven"
    description = "A blog about..."
    bgimg = "img/ignasi_pattern_s.png"

[markup]
  [markup.highlight]
    style = "igor"
